### ISSUE TITLE
Can't execute workflow on Ubuntu 18.04

### ISSUE THREAD

**Issue by gokhangerdan** [knime/knimepy#16]
I tried to execute knime workflow with and without input/output container but I received this:

WARNING:root:Return code from KNIME execution was non-zero
WARNING:root:captured stdout: b''
WARNING:root:captured stderr: b'/bin/sh: 1: /home/ggerdan/knime_4.0.0.linux.gtk.x86_64/knime_4.0.0: Permission denied\n'

**Comment by applio** [comment]
Is the name of the executable "knime_4.0.0" or might it be "knime_4.0.0/knime"?

**Comment by gokhangerdan** [comment]
Of course not :sweat_smile:
I gave the path that contains the executable…
I changed it to “/home/ggerdan/knime_4.0.0.linux.gtk.x86_64/knime_4.0.0/knime”
And now it runs without any error.
Thanks for your time and attention.
